### ISSUE TITLE
版本更新升级教程

### ISSUE THREAD

**Issue by dbccccccc** [trueai-org/midjourney-proxy#15]
作者能不能写一个更新教程，描述在更新版本时需要迁移哪些文件等等

**Comment by trueai-org** [comment]
OK，可以的

**Comment by trueai-org** [comment]
### 目录结构

在版本升级之前，首先了解目录结构。

1. 系统必要的文件包括 2 个文件：`mj.db`、`appsettings.json` 或 `appsettings.Production.json`，存放任务、账号池等信息。
2. `appsettings.json` 与 `appsettings.Production.json` 说明，如果你使用了 `appsettings.Production.json` 配置，则可以忽略 `appsettings.json`
3. 图片文件，只有开启图片保存到本地时，此目录下才有图片，包含目录：`attachments`、`ephemeral-attachments`

- `appsettings.json` 默认配置
- `appsettings.Production.json` 生产环境配置
- `/app/data` 数据目录，存放账号、任务等数据
    - `/app/data/mj.db` 数据库文件
- `/app/logs` 日志目录
- `/app/wwwroot` 静态文件目录
    - `/app/wwwroot/attachments` 绘图文件目录
    - `/app/wwwroot/ephemeral-attachments` describe 生成图片目录

### Docker 升级说明
```bash
# 1. 重新拉取最新镜像
docker pull registry.cn-guangzhou.aliyuncs.com/trueai-org/midjourney-proxy

# 2. 删除容器（确保映射了配置文件和数据库文件）
docker stop mjopen && docker rm mjopen

# 3. 重新启动一个新的容器
docker run -m 1g --name mjopen -d --restart=always \
 -e DEMO=true \
 -p 8086:8080 --user root \
 -v /root/mjopen/logs:/app/logs:rw \
 -v /root/mjopen/data:/app/data:rw \
 -v /root/mjopen/attachments:/app/wwwroot/attachments:rw \
 -v /root/mjopen/ephemeral-attachments:/app/wwwroot/ephemeral-attachments:rw \
 -v /root/mjopen/appsettings.Production.json:/app/appsettings.Production.json:ro \
 -e TZ=Asia/Shanghai \
 -v /etc/localtime:/etc/localtime:ro \
 -v /etc/timezone:/etc/timezone:ro \
 registry.cn-guangzhou.aliyuncs.com/trueai-org/midjourney-proxy
```

### 其他版本升级

```bash
# 1. 下载最新版本后

# 2.1 如果你使用的是 `appsettings.Production.json` 配置文件，则选择全部覆盖。

# 2.2 如果你使用的是 `appsettings.json` 配置文件，注意删除默认的  `appsettings.json` 配置文件，保留你本地的配置文件即可。
```

**Comment by dbccccccc** [comment]
`appsettings.Production.json`是一个用户自定义的配置文件吗？`appsettings.json`作为发行版本中的默认配置文件示例，是不是只有当用户没有提供`appsettings.Production.json`文件，程序会寻找`appsettings.json`作为替代？也就是说，这两个文件在内容上是一样的？`appsettings.Production.json`只在docker版本配置教程中有提及，如果其他方式部署的用户看到这个教程可能会有点懵，建议可以添加说明。

**Comment by trueai-org** [comment]
已经补充了

**Comment by dbccccccc** [comment]
ok，谢谢作者

**Comment by trueai-org** [comment]
- docker 一键升级脚本，注意修改或删除改为你自己的参数，参考：<https://raw.githubusercontent.com/trueai-org/midjourney-proxy/main/scripts/docker_upgrade.sh>

```bash
#!/bin/bash

# 定义一些变量
IMAGE_NAME="registry.cn-guangzhou.aliyuncs.com/trueai-org/midjourney-proxy"
CONTAINER_NAME="mjopen"

# 打印信息
echo "开始更新 ${CONTAINER_NAME} 容器..."

# 验证Docker是否安装
if ! command -v docker &> /dev/null
then
    echo "Docker 未安装，请先安装 Docker。"
    exit 1
fi

# 拉取最新镜像
echo "拉取最新的镜像 ${IMAGE_NAME}..."
docker pull ${IMAGE_NAME}
if [ $? -ne 0 ]; then
    echo "拉取镜像失败，请检查网络连接或镜像地址是否正确。"
    exit 1
fi

# 停止并移除现有容器
if [ "$(docker ps -q -f name=${CONTAINER_NAME})" ]; then
    echo "停止现有的容器 ${CONTAINER_NAME}..."
    docker stop ${CONTAINER_NAME}
    if [ $? -ne 0 ]; then
        echo "停止容器失败，请手动检查。"
        exit 1
    fi
fi

if [ "$(docker ps -aq -f status=exited -f name=${CONTAINER_NAME})" ]; then
    echo "移除现有的容器 ${CONTAINER_NAME}..."
    docker rm ${CONTAINER_NAME}
    if [ $? -ne 0 ]; then
        echo "移除容器失败，请手动检查。"
        exit 1
    fi
fi

# 运行新的容器
echo "启动新的容器 ${CONTAINER_NAME}..."
docker run -m 1g --name ${CONTAINER_NAME} -d --restart=always \
 -e DEMO=true \
 -p 8086:8080 --user root \
 -v /root/mjopen/logs:/app/logs:rw \
 -v /root/mjopen/data:/app/data:rw \
 -v /root/mjopen/attachments:/app/wwwroot/attachments:rw \
 -v /root/mjopen/ephemeral-attachments:/app/wwwroot/ephemeral-attachments:rw \
 -v /root/mjopen/appsettings.Production.json:/app/appsettings.Production.json:ro \
 -e TZ=Asia/Shanghai \
 -v /etc/localtime:/etc/localtime:ro \
 -v /etc/timezone:/etc/timezone:ro \
 ${IMAGE_NAME}
if [ $? -ne 0 ]; then
    echo "启动新的容器失败，请手动检查。"
    exit 1
fi

echo "容器 ${CONTAINER_NAME} 更新并启动成功！"


```

**Comment by trueai-org** [comment]
- docker-compose.yml

```
version: '3'
services:
  mjopen:
    image: registry.cn-guangzhou.aliyuncs.com/trueai-org/midjourney-proxy
    container_name: mjopen
    restart: always
    environment:
      - DEMO=true
      - TZ=Asia/Shanghai
    ports:
      - "8086:8080"
    volumes:
      - /root/mjopen/logs:/app/logs:rw
      - /root/mjopen/data:/app/data:rw
      - /root/mjopen/attachments:/app/wwwroot/attachments:rw
      - /root/mjopen/ephemeral-attachments:/app/wwwroot/ephemeral-attachments:rw
      - /root/mjopen/appsettings.Production.json:/app/appsettings.Production.json:ro
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
```
